# Generated by Django 3.2.3 on 2021-05-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StellarAccount',
            fields=[
                ('public_key', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('has_sq_badges', models.BooleanField(default=False)),
                ('badges', models.JSONField()),
                ('nickname', models.CharField(max_length=64)),
                ('directory_name', models.CharField(max_length=64)),
                ('directory_tags', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField()),
                ('operation_id', models.BigIntegerField()),
                ('memo', models.CharField(max_length=64)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_payments', to='scanner.stellaraccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='scanner.stellaraccount')),
            ],
        ),
    ]
