# Generated by Django 3.2.3 on 2021-05-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_rename_badges_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='asset_code',
            field=models.CharField(max_length=6),
        ),
    ]
