# Generated by Django 3.2.3 on 2021-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_badge_asset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default='0 XLM', help_text='Decimal amount including Asset Code', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='directory_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='directory_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
