# Generated by Django 3.2.3 on 2021-05-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_auto_20210525_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='operation_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='transaction_hash',
        ),
    ]
