# Generated by Django 3.2.3 on 2021-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_auto_20210525_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='memo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_hash',
            field=models.CharField(max_length=64),
        ),
    ]
