# Generated by Django 3.2.3 on 2021-05-25 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_auto_20210525_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 12, 30, 2, 485629)),
            preserve_default=False,
        ),
    ]
