# Generated by Django 3.2.3 on 2021-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_payment_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
