# Generated by Django 3.2.3 on 2021-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellaraccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stellaraccount',
            name='suspect',
            field=models.BooleanField(default=False),
        ),
    ]
