# Generated by Django 3.2.3 on 2021-05-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_stellaraccount_kosher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stellaraccount',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='directory_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
